/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PurchaseCompleteRouteImport } from './routes/purchase-complete'
import { Route as EnrollRouteImport } from './routes/enroll'
import { Route as CurriculumRouteImport } from './routes/curriculum'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedCourseIndexRouteImport } from './routes/_authenticated/course.index'
import { Route as AuthenticatedCourseSlugRouteImport } from './routes/_authenticated/course.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseCompleteRoute = PurchaseCompleteRouteImport.update({
  id: '/purchase-complete',
  path: '/purchase-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollRoute = EnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumRoute = CurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCourseIndexRoute =
  AuthenticatedCourseIndexRouteImport.update({
    id: '/course/',
    path: '/course/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCourseSlugRoute = AuthenticatedCourseSlugRouteImport.update({
  id: '/course/$slug',
  path: '/course/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/curriculum': typeof CurriculumRoute
  '/enroll': typeof EnrollRoute
  '/purchase-complete': typeof PurchaseCompleteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/course/$slug': typeof AuthenticatedCourseSlugRoute
  '/course/': typeof AuthenticatedCourseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/curriculum': typeof CurriculumRoute
  '/enroll': typeof EnrollRoute
  '/purchase-complete': typeof PurchaseCompleteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/course/$slug': typeof AuthenticatedCourseSlugRoute
  '/course': typeof AuthenticatedCourseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/curriculum': typeof CurriculumRoute
  '/enroll': typeof EnrollRoute
  '/purchase-complete': typeof PurchaseCompleteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/course/$slug': typeof AuthenticatedCourseSlugRoute
  '/_authenticated/course/': typeof AuthenticatedCourseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/curriculum'
    | '/enroll'
    | '/purchase-complete'
    | '/sitemap.xml'
    | '/course/$slug'
    | '/course/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/curriculum'
    | '/enroll'
    | '/purchase-complete'
    | '/sitemap.xml'
    | '/course/$slug'
    | '/course'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/curriculum'
    | '/enroll'
    | '/purchase-complete'
    | '/sitemap.xml'
    | '/_authenticated/course/$slug'
    | '/_authenticated/course/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CurriculumRoute: typeof CurriculumRoute
  EnrollRoute: typeof EnrollRoute
  PurchaseCompleteRoute: typeof PurchaseCompleteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-complete': {
      id: '/purchase-complete'
      path: '/purchase-complete'
      fullPath: '/purchase-complete'
      preLoaderRoute: typeof PurchaseCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enroll': {
      id: '/enroll'
      path: '/enroll'
      fullPath: '/enroll'
      preLoaderRoute: typeof EnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum': {
      id: '/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof CurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/course/': {
      id: '/_authenticated/course/'
      path: '/course'
      fullPath: '/course/'
      preLoaderRoute: typeof AuthenticatedCourseIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/course/$slug': {
      id: '/_authenticated/course/$slug'
      path: '/course/$slug'
      fullPath: '/course/$slug'
      preLoaderRoute: typeof AuthenticatedCourseSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCourseSlugRoute: typeof AuthenticatedCourseSlugRoute
  AuthenticatedCourseIndexRoute: typeof AuthenticatedCourseIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCourseSlugRoute: AuthenticatedCourseSlugRoute,
  AuthenticatedCourseIndexRoute: AuthenticatedCourseIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CurriculumRoute: CurriculumRoute,
  EnrollRoute: EnrollRoute,
  PurchaseCompleteRoute: PurchaseCompleteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
